coverage:
  status:
    patch: off
    project:
      default:
        threshold: 5%
codecov:
  require_ci_to_pass: false
comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
ignore:
  - "api"
  - "playwright"
  - "src/store"
