const UPDATE_COMPOSE = 'UPDATE_COMPOSE';
const SET_RELEASE = 'SET_RELEASE';
const SET_UPLOAD_DESTINATIONS = 'SET_UPLOAD_DESTINATIONS';
const SET_UPLOAD_AWS = 'SET_UPLOAD_AWS';
const SET_UPLOAD_AZURE = 'SET_UPLOAD_AZURE';
const SET_UPLOAD_GOOGLE = 'SET_UPLOAD_GOOGLE';
const SET_SELECTED_PACKAGES = 'SET_SELECTED_PACKAGES';
const SET_SUBSCRIPTION = 'SET_SUBSCRIPTION';
const SET_SUBSCRIBE_NOW = 'SET_SUBSCRIBE_NOW';

export default {
    UPDATE_COMPOSE,
    SET_RELEASE,
    SET_UPLOAD_DESTINATIONS,
    SET_UPLOAD_AWS,
    SET_UPLOAD_AZURE,
    SET_UPLOAD_GOOGLE,
    SET_SELECTED_PACKAGES,
    SET_SUBSCRIPTION,
    SET_SUBSCRIBE_NOW,
};
