const COMPOSE_ADDED = 'COMPOSE_ADDED';
const COMPOSE_FAILED = 'COMPOSE_FAILED';
const COMPOSE_UPDATED = 'COMPOSE_UPDATED';
const COMPOSES_UPDATED_COUNT = 'COMPOSES_UPDATED_COUNT';
const COMPOSE_UPDATED_STATUS = 'COMPOSE_UPDATED_STATUS';
const SET_RELEASE = 'SET_RELEASE';
const SET_UPLOAD_DESTINATIONS = 'SET_UPLOAD_DESTINATIONS';
const SET_UPLOAD_AWS = 'SET_UPLOAD_AWS';
const SET_UPLOAD_AZURE = 'SET_UPLOAD_AZURE';
const SET_UPLOAD_GOOGLE = 'SET_UPLOAD_GOOGLE';
const SET_SELECTED_PACKAGES = 'SET_SELECTED_PACKAGES';
const SET_SUBSCRIPTION = 'SET_SUBSCRIPTION';
const SET_SUBSCRIBE_NOW = 'SET_SUBSCRIBE_NOW';

export default {
  COMPOSE_ADDED,
  COMPOSE_FAILED,
  COMPOSE_UPDATED,
  COMPOSES_UPDATED_COUNT,
  COMPOSE_UPDATED_STATUS,
  SET_RELEASE,
  SET_UPLOAD_DESTINATIONS,
  SET_UPLOAD_AWS,
  SET_UPLOAD_AZURE,
  SET_UPLOAD_GOOGLE,
  SET_SELECTED_PACKAGES,
  SET_SUBSCRIPTION,
  SET_SUBSCRIBE_NOW,
};
