name: "Create GitHub release"

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # create release artefact before creating the release to get the correct release in the
      # artefact name.
      - uses: actions/checkout@v7

      - name: Setup Node.js with cached dependencies
        uses: ./.github/actions/setup-node-cached

      - name: Make dist
        run: |
          RELEASE_NO=$(echo ${{github.ref_name}} | tr -d 'v')
          make dist VERSION=$RELEASE_NO
          mv "cockpit-image-builder-$RELEASE_NO.tar.gz" ../cockpit-image-builder-$RELEASE_NO.tar.gz

      - name: Discover branch for release action
        run: |
          COMMIT=$(git rev-parse ${{ github.ref_name }})
          BRANCH=$(git branch --points-at "$COMMIT")
          RESULT=${BRANCH:-main}
          echo "RELEASE_BRANCH=$RESULT" >> $GITHUB_OUTPUT
          echo running upstream release against "$RESULT" branch

      # create release, which will bump the version
      - name: Upstream release
        uses: osbuild/release-action@main
        with:
          token: "${{ secrets.SCHUTZBOT_GITHUB_ACCESS_TOKEN }}"
          slack_bot_token: "${{ secrets.SLACK_BOT_TOKEN }}"
          branch: ${{ needs.release.outputs.RELEASE_BRANCH }}

      - name: Upload release artefact
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_NO=$(echo ${{ github.ref_name }} | tr -d 'v')
          gh release upload ${{ github.ref_name }} \
            ../cockpit-image-builder-$RELEASE_NO.tar.gz
